# This file was generated by GoReleaser. DO NOT EDIT.
cask "aaswap" do
  version "0.7.0"

  on_macos do
    on_arm do
      sha256 "f93f2bd2d28371aeb3d0a66552669729ccfff17efdcf153fdb8eb7a6405bbe5d"
      url "https://github.com/d0lim/aaswap/releases/download/v#{version}/aaswap_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "21bd82c583e41b1c842e0fbd0d059a9d7172c25fb72c71387c306659c2399391"
      url "https://github.com/d0lim/aaswap/releases/download/v#{version}/aaswap_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "93d5205f26bdb0dcce299e9fef6df41430d18ae272aa84c5ab35e08e30661348"
      url "https://github.com/d0lim/aaswap/releases/download/v#{version}/aaswap_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "bb729821465f12cf5b1163c5bb0256ad54e7efd5a6d246a004c73ddb82284e5a"
      url "https://github.com/d0lim/aaswap/releases/download/v#{version}/aaswap_#{version}_linux_amd64.tar.gz"
    end
  end

  name "aaswap"
  desc "Manage several agent CLI logins (Claude Code, Codex) on one machine"
  homepage "https://github.com/d0lim/aaswap"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aaswap"

  postflight do
    if OS.mac?
      # The binaries are not signed or notarized, so Gatekeeper
      # quarantines them and the first run dies with "cannot be opened".
      # Homebrew downloaded this itself; clearing the flag it set is the
      # documented way for an unsigned cask to be runnable at all.
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/aaswap"]
    end
  end

  # No zap stanza required
end
