# This file was generated by GoReleaser. DO NOT EDIT.
cask "aaswap" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "2ce650058b2b4dd7543699c8b403ce6f23308caba29c71b142084f459733f496"
      url "https://github.com/d0lim/aaswap/releases/download/v#{version}/aaswap_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/d0lim/aaswap/"
    end
    on_intel do
      sha256 "d5709824206caa7127f9e7992d518643e3a9b9cfe738814ccf9dc33b9170329e"
      url "https://github.com/d0lim/aaswap/releases/download/v#{version}/aaswap_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/d0lim/aaswap/"
    end
  end
  on_linux do
    on_arm do
      sha256 "99b45c899351a8602fd144e074314684a7b820961c990e8bde70aa18d622b2f5"
      url "https://github.com/d0lim/aaswap/releases/download/v#{version}/aaswap_#{version}_linux_arm64.tar.gz",
        verified: "github.com/d0lim/aaswap/"
    end
    on_intel do
      sha256 "789960f095861ac4d954d80900b7e5708ac3e537563e5dec89834822bcbf53de"
      url "https://github.com/d0lim/aaswap/releases/download/v#{version}/aaswap_#{version}_linux_amd64.tar.gz",
        verified: "github.com/d0lim/aaswap/"
    end
  end

  name "aaswap"
  desc "Manage several agent CLI logins (Claude Code, Codex) on one machine"
  homepage "https://github.com/d0lim/aaswap"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aaswap"

  postflight do
    if OS.mac?
      # The binaries are not signed or notarized, so Gatekeeper
      # quarantines them and the first run dies with "cannot be opened".
      # Homebrew downloaded this itself; clearing the flag it set is the
      # documented way for an unsigned cask to be runnable at all.
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/aaswap"]
    end
  end

  # No zap stanza required
end
