# This file was generated by GoReleaser. DO NOT EDIT.
cask "aaswap" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "264697e5b9f38a081df0c8aabf70c0981ed5516e78d55c6ccd5c23d642be036e"
      url "https://github.com/d0lim/aaswap/releases/download/v#{version}/aaswap_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/d0lim/aaswap/"
    end
    on_intel do
      sha256 "e6191c5820255291436970f5ef64850c71acd0159dd6cb7fd39bf112b0d06bcd"
      url "https://github.com/d0lim/aaswap/releases/download/v#{version}/aaswap_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/d0lim/aaswap/"
    end
  end
  on_linux do
    on_arm do
      sha256 "074afd35167a7fbb5b791e8f10ebf2ab6f38494cb44d37b0338aa624f702f1a6"
      url "https://github.com/d0lim/aaswap/releases/download/v#{version}/aaswap_#{version}_linux_arm64.tar.gz",
        verified: "github.com/d0lim/aaswap/"
    end
    on_intel do
      sha256 "04465784cef5ec76733b464983bff685783652ff144b706c48a00f0d40079b6d"
      url "https://github.com/d0lim/aaswap/releases/download/v#{version}/aaswap_#{version}_linux_amd64.tar.gz",
        verified: "github.com/d0lim/aaswap/"
    end
  end

  name "aaswap"
  desc "Manage several agent CLI logins (Claude Code, Codex) on one machine"
  homepage "https://github.com/d0lim/aaswap"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aaswap"

  postflight do
    if OS.mac?
      # The binaries are not signed or notarized, so Gatekeeper
      # quarantines them and the first run dies with "cannot be opened".
      # Homebrew downloaded this itself; clearing the flag it set is the
      # documented way for an unsigned cask to be runnable at all.
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/aaswap"]
    end
  end

  # No zap stanza required
end
