# Generated by GoReleaser for the last release under the old name, then edited
# once by hand to deprecate it. GoReleaser now emits Casks/aaswap.rb and never
# touches this file again.
#
# The download URLs still resolve: GitHub redirects d0lim/ccswap to
# d0lim/aaswap, and the v0.2.0 release keeps its ccswap_* assets. So an
# existing install keeps working and `brew upgrade` has nothing to do — it is
# the deprecation notice that tells the person where the project went.
cask "ccswap" do
  version "0.2.0"

  deprecate! date: "2026-09-02", because: "was renamed to aaswap",
             replacement_cask: "d0lim/tap/aaswap"

  on_macos do
    on_arm do
      sha256 "32e7cc56f018f31ad1e61a50ee8acb930654c969d959a2a5ef3bff7a59f0e704"
      url "https://github.com/d0lim/ccswap/releases/download/v#{version}/ccswap_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/d0lim/ccswap/"
    end
    on_intel do
      sha256 "9304d4f551ef69fa3f7830ff8c4a961b53aa0e7f78abff2570496b99298db39c"
      url "https://github.com/d0lim/ccswap/releases/download/v#{version}/ccswap_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/d0lim/ccswap/"
    end
  end
  on_linux do
    on_arm do
      sha256 "3ad25514c0c05367c7aeba12a975a5f1230504f520ef2f3ad943eb1497d7c655"
      url "https://github.com/d0lim/ccswap/releases/download/v#{version}/ccswap_#{version}_linux_arm64.tar.gz",
        verified: "github.com/d0lim/ccswap/"
    end
    on_intel do
      sha256 "89b271fdba6a3925c109f29a24215206054f9a444d28fd72a0db1773e4d1a905"
      url "https://github.com/d0lim/ccswap/releases/download/v#{version}/ccswap_#{version}_linux_amd64.tar.gz",
        verified: "github.com/d0lim/ccswap/"
    end
  end

  name "ccswap"
  desc "Switch between multiple Claude Code accounts"
  homepage "https://github.com/d0lim/ccswap"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccswap"

  postflight do
    if OS.mac?
      # The binaries are not signed or notarized, so Gatekeeper
      # quarantines them and the first run dies with "cannot be opened".
      # Homebrew downloaded this itself; clearing the flag it set is the
      # documented way for an unsigned cask to be runnable at all.
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/ccswap"]
    end
  end

  # No zap stanza required
end
