# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccswap" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "1969e922739a644898b3592f07d35b5b1d3acae4ae66ad7b9311020da53afaee"
      url "https://github.com/d0lim/ccswap/releases/download/v#{version}/ccswap_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/d0lim/ccswap/"
    end
    on_intel do
      sha256 "92f3eda9476dda30b3ca8420334dbf0e5ef629d66c9d1d228023bd0ca77d541a"
      url "https://github.com/d0lim/ccswap/releases/download/v#{version}/ccswap_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/d0lim/ccswap/"
    end
  end
  on_linux do
    on_arm do
      sha256 "4f2dbda8f25e49ec9b62571667814a9973cc3d3a188b9d8b622d790a498b2866"
      url "https://github.com/d0lim/ccswap/releases/download/v#{version}/ccswap_#{version}_linux_arm64.tar.gz",
        verified: "github.com/d0lim/ccswap/"
    end
    on_intel do
      sha256 "291179695036e7ee86fd918da5a9a660eeb8d0033bb7475be2b060cadee6df2e"
      url "https://github.com/d0lim/ccswap/releases/download/v#{version}/ccswap_#{version}_linux_amd64.tar.gz",
        verified: "github.com/d0lim/ccswap/"
    end
  end

  name "ccswap"
  desc "Switch between multiple Claude Code accounts"
  homepage "https://github.com/d0lim/ccswap"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccswap"

  postflight do
    if OS.mac?
      # The binaries are not signed or notarized, so Gatekeeper
      # quarantines them and the first run dies with "cannot be opened".
      # Homebrew downloaded this itself; clearing the flag it set is the
      # documented way for an unsigned cask to be runnable at all.
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/ccswap"]
    end
  end

  # No zap stanza required
end
