# Generated by scripts/update-cask.sh in d0lim/display-remember.
cask "display-remember" do
  version "0.4.0"
  sha256 "ea48a12de2ff5cee2d09936f4e9d736640f5bd153de9bc51928b786d129dba6e"

  url "https://github.com/d0lim/display-remember/releases/download/v#{version}/display-remember-#{version}-arm64.zip"
  name "display-remember"
  desc "Remember physical monitors and restore their layouts"
  homepage "https://github.com/d0lim/display-remember"

  depends_on arch: :arm64
  depends_on macos: :ventura

  app "display-remember.app"
  binary "#{appdir}/display-remember.app/Contents/MacOS/display-remember"

  zap trash: [
    "~/Library/Application Support/display-remember",
    "~/Library/Preferences/dev.d0lim.display-remember.plist",
    "~/Library/Saved Application State/dev.d0lim.display-remember.savedState",
  ]
end
