# Generated by scripts/update-cask.sh in d0lim/display-remember.
cask "display-remember" do
  version "0.6.0"
  sha256 "6173c27f93ad28562bd7a9a5337c7204360ae60a836c8ae7c9c1554287c6e84d"

  url "https://github.com/d0lim/display-remember/releases/download/v#{version}/display-remember-#{version}-arm64.zip"
  name "Display Remember"
  desc "Remember physical monitors and restore their layouts"
  homepage "https://github.com/d0lim/display-remember"

  depends_on arch: :arm64
  depends_on macos: :ventura

  app "Display Remember.app"
  binary "#{appdir}/Display Remember.app/Contents/MacOS/display-remember"

  zap trash: [
    "~/Library/Application Support/display-remember",
    "~/Library/Preferences/dev.d0lim.display-remember.plist",
    "~/Library/Saved Application State/dev.d0lim.display-remember.savedState",
  ]
end
