# Generated by scripts/update-cask.sh in d0lim/display-remember.
cask "display-remember" do
  version "0.5.0"
  sha256 "2d160a689b28f6705f010969105ebf8eefcd7db16ae908200113d7ebcb8faafd"

  url "https://github.com/d0lim/display-remember/releases/download/v#{version}/display-remember-#{version}-arm64.zip"
  name "display-remember"
  desc "Remember physical monitors and restore their layouts"
  homepage "https://github.com/d0lim/display-remember"

  depends_on arch: :arm64
  depends_on macos: :ventura

  app "display-remember.app"
  binary "#{appdir}/display-remember.app/Contents/MacOS/display-remember"

  zap trash: [
    "~/Library/Application Support/display-remember",
    "~/Library/Preferences/dev.d0lim.display-remember.plist",
    "~/Library/Saved Application State/dev.d0lim.display-remember.savedState",
  ]
end
