# Generated by scripts/update-cask.sh in d0lim/garakuta. Edit there, not here.
cask "garakuta" do
  version "0.6.1"
  sha256 "13487804edab1ee3c1dfcf9aa00658d8a52b489aeb2ce9f2b1b053200ab80300"

  url "https://github.com/d0lim/garakuta/releases/download/v#{version}/Garakuta-#{version}.zip"
  name "Garakuta"
  desc "Menu bar organizer, notch panel and window switcher"
  homepage "https://github.com/d0lim/garakuta"

  livecheck do
    url :url
    strategy :github_latest
  end

  depends_on macos: :sequoia

  app "Garakuta.app"

  postflight_steps do
    # The app is ad-hoc signed, so Gatekeeper quarantines the download and refuses to open it.
    # Homebrew fetched the archive itself; clearing the flag it set is the documented way to make
    # an unsigned cask runnable.
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{appdir}}/Garakuta.app"]
  end

  zap trash: [
    "~/Library/Application Support/Garakuta",
    "~/Library/Preferences/com.d0lim.garakuta.plist",
  ]

  caveats <<~EOS
    Garakuta needs Accessibility permission for menu bar item management and
    the window switcher. The setup assistant on first launch asks for it.
    Quit any other menu bar manager or Option-Tab switcher before enabling
    the matching Garakuta module.
  EOS
end
